language: generic

sudo: required
servives:
    - docker

before_install:
    - docker build -t uks/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true uks/docker-react npm run test
